version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    working_dir: /home/appuser/src
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/home/appuser/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    # This overrides the REDIS_URL from the .env file FOR THE CONTAINER
    environment:
      - REDIS_URL=redis://redis:6379/0

  worker:
    build: .
    working_dir: /home/appuser/src
    command: python -m celery -A app.core.celery_app:celery_app worker --loglevel=info
    volumes:
      - ./app:/home/appuser/src/app
    depends_on:
      - redis
    env_file:
      - .env
    # This overrides the REDIS_URL from the .env file FOR THE CONTAINER
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis_data: