services:
  - type: redis
    name: redis-cache
    plan: free 
    ipAllowList: [] 
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: code-review-api
    env: python
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /docs
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: GEMINI_API_KEY 
        sync: false 
      - key: GITHUB_ACCESS_TOKEN 
        sync: false 

 
  - type: web 
    name: celery-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m celery -A app.core.celery_app:celery_app worker --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: GITHUB_ACCESS_TOKEN
        sync: false
